# Copyright 2024 Cisco Systems, Inc. and its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tabularium
  labels:
    app: tabularium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tabularium
  template:
    metadata:
      labels:
        app: tabularium
    spec:
      containers:
        - name: tabularium
          image: <username>/tabularium:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: db_root_password
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: db_root_password
            - name: db_name
              value: amlllmdefense
---
apiVersion: v1
kind: Service
metadata:
  name: tabularium
spec:
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: tabularium
  type: LoadBalancer
